# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build whole site

on:
  push:
    branches:
      - cicd-testing
  workflow_dispatch:

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ausrunswebsitecontainersregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      -
        name: Build NextJS and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ausrunswebsitecontainersregistry/ausruns/next:latest
          cache-from: type=registry,ref=ausrunswebsitecontainersregistry/ausruns/next:latest
          cache-to: type=inline
          secrets: |
            "DATABASE_URL=${{ secrets.DATABASE_URL }}"
            "SESSION_SECRET=${{ secrets.SESSION_SECRET }}"
            "API_KEY=${{ secrets.API_KEY }}"
            "NEXT_PUBLIC_STRIPE_PUBLIC_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLIC_KEY }}"
      -
        name: Build KeystoneJS and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ausrunswebsitecontainersregistry/ausruns/keystone:latest
          file: "Dockerfile.keystone"
          cache-from: type=registry,ref=ausrunswebsitecontainersregistry/ausruns/keystone:latest
          cache-to: type=inline
          secrets: |
            "DATABASE_URL=${{ secrets.DATABASE_URL }}"
            "SESSION_SECRET=${{ secrets.SESSION_SECRET }}"

